name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        services:
          chrome:
            image: selenium/standalone-chrome
            ports:
              - 4444:4444

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up JDK 22
              uses: actions/setup-java@v3
              with:
                java-version: 22
                distribution: 'temurin'

            - name: Build with Maven
              run: mvn clean install

            - name: Run tests
              run: mvn test